### ISSUE TITLE
High image count

### ISSUE THREAD

**Issue by lawloretienne** [jjhesk/LoyalNativeSlider#1]
How does your library account for dozens of images?  Lets say you had something like 60 images in the slider.  What happens to the circle page indicator?  What does that look like?

**Comment by jjhesk** [comment]
yes, i have not covered that yet. I think it a good idea to make the options to be 
1) flexiable - give its options to be flexible to choose from the data size.
2) force dots - presents in dots no more than 6 images
3) force number counts - presents in image counts with the format xx/xx. I think the layouts should be able to implemented by user side. The default option should on the bottom right side.

You will have to wait a bit for me to add that otherwise you can go ahead to make your PR. 
I suggest to start from here: 
- [x] add the new indicator form this [folder](https://github.com/jjhesk/LoyalNativeSlider/tree/master/library/src/main/java/com/hkm/slider/Indicators)
- [x] implement the options in the [sliderlayout.java](https://github.com/jjhesk/LoyalNativeSlider/blob/master/library/src/main/java/com/hkm/slider/SliderLayout.java)

Thanks for kind your suggestion!

**Comment by jjhesk** [comment]
Feel free to PR to the [dev branch](https://github.com/jjhesk/LoyalNativeSlider/tree/dev)

**Comment by jjhesk** [comment]
@lawloretienne do you mean the circle page indicator as the dots?

**Comment by lawloretienne** [comment]
yes the dots at the bottom

**Comment by jjhesk** [comment]
those are the indicators from the given choices.  You can add your options in here 

``` java

        mDemoSlider.setPresetIndicator(SliderLayout.PresetIndicators.Center_Bottom);
```

**Comment by aldocano** [comment]
Do you have any idea on resolving this part, i try loading 77 images :smile: and got a Out of memory :stop_sign:
